name: terraform-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: 1.7.5
  ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=env/${{ matrix.environment }} init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform -chdir=env/${{ matrix.environment }} plan -out=tfplan

  docs:
    runs-on: ubuntu-latest
    needs: terraform   # ensures docs run after terraform job succeeds
    steps:
      - uses: actions/checkout@v4

      - name: Generate module docs
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: modules/vnet
          output-file: README.md
          output-method: replace  # only updates the TF_DOCS section

      - name: Upload README artifact
        uses: actions/upload-artifact@v3
        with:
          name: module-docs
          path: modules/vnet/README.md