name: terraform-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allow manual trigger

env:
  TF_VERSION: 1.7.5
  ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev ]  # add more environments as needed

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # Initialize Terraform for this environment
      - name: Terraform Init
        run: terraform -chdir=env/${{ matrix.environment }} init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform -chdir=env/${{ matrix.environment }} plan -out=tfplan

