name: terraform-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_VERSION: 1.7.5
  ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [ dev ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=env/${{ matrix.environment }} init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform -chdir=env/${{ matrix.environment }} plan -out=tfplan

  docs:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4

      - name: Generate module docs
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          working-dir: modules/vnet
          output-file: README.md
          output-method: replace

      - name: Commit & Push updated docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add modules/vnet/README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update terraform-docs"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
