name: terraform-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  TF_VERSION: 1.7.5
  ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [ dev ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform -chdir=env/${{ matrix.environment }} init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform -chdir=env/${{ matrix.environment }} plan -out=tfplan

  docs:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - name: Checkout (with write access)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Mark workspace safe for Git
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Install terraform-docs
        run: |
          curl -sSL https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-v0.16.0-linux-amd64.tar.gz \
            | tar -xz --to-stdout terraform-docs > terraform-docs && chmod +x terraform-docs && sudo mv terraform-docs /usr/local/bin/

      - name: Generate module docs
        run: terraform-docs markdown table --output-file README.md .

      - name: Commit & Push updated docs
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add modules/vnet/README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: update terraform-docs"
            git push origin HEAD:main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
