name: terraform-deploy

on:
  push:
    branches: [ main ]
  pull_request:

env:
  ARM_CLIENT_ID:   ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID:   ${{ secrets.ARM_TENANT_ID }}
  TF_VERSION: 1.7.5

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./envs/dev   # switch per environment
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        # run: terraform init -backend-config="resource_group_name=rg-dev-eastus" -backend-config="storage_account_name=<state‑sa>" -backend-config="container_name=tfstate" -backend-config="key=dev.terraform.tfstate"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -out tfplan
